import turtle
t=turtle.Turtle()
t.color("black")

screen=turtle.Screen()
screen.setup(1500,1000)
screen.bgcolor('red')
t.penup()
t.setpos(0,0)
t.pendown()
t.pencolor('white')
t.pensize(4)
t.shape('turtle')
t.penup()
t.setpos(0,-300)
t.pendown()
t.fillcolor('white')
t.begin_fill()
t.circle(300)
t.end_fill()
t.penup()
t.setpos(0,0)
t.pendown()
t.pencolor('black')
t.pensize(50)
t.right(45)
for i in range(4):
  t.forward(150)
  t.right(90)
  t.forward(150)
  t.penup()
  t.setpos(0, 0)
  t.tilt(90)
  t.pendown()

t.fillcolor('black')
turtle.done()

